# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/martyngigg/pre-commit-clang-format
    rev: daef541c33ebfc94532ce25327bdb1a10ad35787
    hooks:
    -   id: clang-format
exclude:
    '^external/.*$'
