# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/martyngigg/pre-commit-clang-format
    rev: 3ce14c8afebf6889e7c95c3920aab235782cde02
    hooks:
    -   id: clang-format
exclude:
    '^external/.*$'
