channels:
  - conda-forge
  - defaults

dependencies:
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - python=3.7
  - cmake=3.14.5
  - h5py=2.9.0
  - hdf5=1.10.4
  - pip=19.1.1
  - pip:
    - cmake-format==0.5.3