# Version number components.
set (PROJECT_NAME_MAJOR_VERSION 0)
set (PROJECT_NAME_MINOR_VERSION 0)
set (PROJECT_NAME_BUILD_VERSION 0)

# Version string
set (PROJECT_NAME ${PROJECT_NAME_MAJOR_VERSION}.${PROJECT_NAME_MINOR_VERSION}.${PROJECT_NAME_BUILD_VERSION})
